version: '3.7'
services:
  front:
    build: ./frontend
    command: npm start
    ports:
      - 3000:3000
    depends_on:
     - back
    tty: true
    links:
      - back
  back:
    build: ./lib_catalog
    command: bash -c "python ./parse_docx.py && python  manage.py loaddata catalog/fixtures/bbk_data.json && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./lib_catalog:/usr/src/app
    ports:
      - 8000:8000
    expose:
      - "8000"
    env_file:
      - ./.env.dev
    depends_on:
      - database
  database:
    image: postgres:12
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
    ports:
      - 5432:5432